"""
ORM models — field names follow PRD section 33 (Suggested Data Objects)
directly, so the schema is traceable back to the spec.
"""
import uuid
from datetime import datetime

from sqlalchemy import Column, String, Integer, Float, DateTime, ForeignKey, JSON, Text
from sqlalchemy.orm import relationship

from .database import Base

# pgvector's SQLAlchemy Vector type only compiles against the postgresql
# dialect — Candidate is created conditionally in main.py (skipped when
# DATABASE_URL is the default local SQLite), see that file for why. Still
# safe to import unconditionally: the pgvector package itself has no
# Postgres-only dependency, only the Vector *type*'s DDL compilation does.
from pgvector.sqlalchemy import Vector

EMBEDDING_DIM = 1536  # text-embedding-3-small


def gen_id():
    return str(uuid.uuid4())


class User(Base):
    __tablename__ = "users"

    id = Column(String, primary_key=True, default=gen_id)
    name = Column(String, nullable=True)
    email = Column(String, nullable=True)
    language = Column(String, default="en")
    location = Column(String, nullable=True)
    gender = Column(String, nullable=True)
    gender_preference = Column(String, nullable=True)
    age = Column(Integer, nullable=True)
    preferred_age_range = Column(String, nullable=True)  # e.g. "30-40"
    blueprint_narrative = Column(Text, nullable=True)  # flowing ideal-partner portrait (schemas.ExtractionResult.narrative)
    created_at = Column(DateTime, default=datetime.utcnow)

    conversations = relationship("Conversation", back_populates="user")
    signals = relationship("BlueprintSignal", back_populates="user")
    discovery_responses = relationship("DiscoveryResponse", back_populates="user")


class Conversation(Base):
    __tablename__ = "conversations"

    id = Column(String, primary_key=True, default=gen_id)
    user_id = Column(String, ForeignKey("users.id"))
    messages = Column(JSON, default=list)  # [{"role": "user"|"assistant", "content": "..."}]
    status = Column(String, default="active")  # active | completed
    created_at = Column(DateTime, default=datetime.utcnow)

    user = relationship("User", back_populates="conversations")


class BlueprintSignal(Base):
    __tablename__ = "blueprint_signals"

    id = Column(String, primary_key=True, default=gen_id)
    user_id = Column(String, ForeignKey("users.id"))
    perspective = Column(String)  # "ME" | "IDEAL_PARTNER"
    category = Column(String)     # personality | lifestyle | physical_type | relationship_dynamic | love_language | dealbreakers | values
    dimension = Column(String, nullable=True)  # e.g. "emotional_expression" (optional, PRD sec 13)
    value = Column(String, nullable=True)      # e.g. "high" (optional, PRD sec 13)
    label = Column(String)        # e.g. "Emotionally expressive"
    strength = Column(String, default="preference")  # hard_requirement | strong_preference | preference | unknown
    source = Column(String)       # "conversation" | "discovery"
    evidence_text = Column(Text, nullable=True)
    confidence = Column(Float, nullable=True)
    created_at = Column(DateTime, default=datetime.utcnow)

    user = relationship("User", back_populates="signals")


class Candidate(Base):
    """A synthetic RAG-matching profile — generated by
    rag_demo/generate_personas.py's self-profile mode, NOT a real user (see
    that file's ingest_candidates() for how these get populated). Postgres/
    pgvector only — see the create_all() guard in main.py for why this
    table doesn't exist on a local SQLite dev DB."""
    __tablename__ = "candidates"

    id = Column(String, primary_key=True, default=gen_id)
    name = Column(String)
    age = Column(Integer)
    gender = Column(String)
    photo_url = Column(String, nullable=True)  # e.g. "/candidates/f1.jpg", served as a static frontend asset
    narrative = Column(Text)  # first-person "who I am" portrait
    signals = Column(JSON)  # list[{category, label, strength, evidence_text}] — this candidate's own PerspectiveBlueprint
    embedding = Column(Vector(EMBEDDING_DIM))  # OpenAIEmbeddings(text-embedding-3-small) over narrative + signal labels
    created_at = Column(DateTime, default=datetime.utcnow)


class Discovery(Base):
    __tablename__ = "discoveries"

    id = Column(String, primary_key=True)  # human-readable slug, e.g. "life_you_are_building"
    title = Column(String)
    status = Column(String, default="active")


class DiscoveryResponse(Base):
    __tablename__ = "discovery_responses"

    id = Column(String, primary_key=True, default=gen_id)
    user_id = Column(String, ForeignKey("users.id"))
    discovery_id = Column(String, ForeignKey("discoveries.id"))
    question_id = Column(String)
    response = Column(Text)
    created_at = Column(DateTime, default=datetime.utcnow)

    user = relationship("User", back_populates="discovery_responses")
